name: MinecraftVNC
main: com.caetsamuel.gmail.VNCraft
description: VNC in Minecraft
author: SecondAmendment
version: 1.0

softdepend: [PacketListenerApi, MapManager]

commands:
   test:
      description: Test command
      usage: /test